language: go
sudo: required
go:
    - "1.9"
    - "1.10"
    - "1.11"
notifications:
    email:
      - sahib@online.de
install:
    - sudo apt-get install fuse
    - go get -u github.com/phogolabs/parcello
    - go get -u github.com/phogolabs/parcello/cmd/parcello
    - go get -d -t -v github.com/sahib/brig
    - go get -u github.com/rakyll/gotest
    - cd $GOPATH/src/github.com/sahib/brig
    - mkdir -p ${GOPATH}/bin
    - export GOBIN=${GOPATH}/bin
    - make

script:
    - cd $GOPATH/src/github.com/sahib/brig
    - export PATH="${GOPATH}/bin:${PATH}"
    - gotest -v ./...
