language: go
sudo: required
go:
    - 1.6
notifications:
    email:
      - sahib@online.de
      - christoph@nullcat.de
install:
    - sudo apt-get install fuse
    - go get -v github.com/Masterminds/glide
    - go get -t -v github.com/disorganizer/brig
script:
    - cd $GOPATH/src/github.com/disorganizer/brig
    - go test -v $(glide novendor)
