language: go
sudo: required
go:
    - 1.5
notifications:
    email:
      - sahib@online.de
      - christoph@nullcat.de
install:
    - go get -t -v ./...
    - sudo apt-get install fuse
script:
    - go test -v github.com/disorganizer/brig/...
