language: go
sudo: required
go:
    - 1.9
notifications:
    email:
      - sahib@online.de
install:
    - sudo apt-get install fuse
    - go get -t -v github.com/disorganizer/brig
script:
    - cd $GOPATH/src/github.com/disorganizer/brig
    - go test -v ./...
