language: go
sudo: required
go:
    - "1.11"
    - "1.12"
notifications:
    email:
      - sahib@online.de
install:
    - sudo apt-get install fuse
    - mkdir -p ${GOPATH}/bin
    - export GOBIN=${GOPATH}/bin
    - go get -u github.com/rakyll/gotest
    - go get -u github.com/phogolabs/parcello
    - go get -u github.com/phogolabs/parcello/cmd/parcello
    - go get -u github.com/ipfs/ipfs-update
    - git clone https://github.com/sahib/brig.git
    - export PATH="${GOPATH}/bin:${PATH}"
    - ipfs-update install v0.4.18
    - cd brig && make

script:
    - cd brig
    - export PATH="${GOPATH}/bin:${PATH}"
    - gotest -v ./...
