baseurl = "https://sahib.github.io/public"
languageCode = "en-us"
title = "brig"

[Params]
  github = "sahib"
  email = "sahib@online.de"
  description = "brig - a decentralized and secure file synchronizer"
  cover = "/public/images/banner.png"
  # logo = "/public/images/geweih.svg"
