baseurl = "https://sahib.github.io/brig/public"
languageCode = "en-us"
title = "brig"


[Params]
  github = "sahib"
  email = "sahib@online.de"
  description = "brig - a decentralized and secure file synchronizer"
  cover = "images/banner.png"
  page_title = "file synchronisation"
