
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "bazil.org/fuse"

[[constraint]]
  branch = "default"
  name = "bitbucket.org/taruti/mimemagic"

[[constraint]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "github.com/VividCortex/godaemon"

[[constraint]]
  branch = "master"
  name = "github.com/alokmenghrajani/gpgeez"

[[constraint]]
  branch = "master"
  name = "github.com/bkaradzic/go-lz4"

[[constraint]]
  branch = "master"
  name = "github.com/chzyer/readline"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  branch = "master"
  name = "github.com/ipfs/go-ipfs-util"

[[constraint]]
  branch = "master"
  name = "github.com/multiformats/go-multihash"

[[constraint]]
  branch = "master"
  name = "github.com/nbutton23/zxcvbn-go"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  branch = "master"
  name = "github.com/pksunkara/pygments"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "github.com/urfave/cli"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/text"

[[constraint]]
  branch = "master"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "zombiezen.com/go/capnproto2"
